### ISSUE TITLE
Show toolbars when moving the mouse to the toolbar (not the tabs area)

### ISSUE THREAD

**Issue by mmssantos** [Quicksaver/The-Fox--Only-Better#160]
When using an additional extension that removes the Tab Bar and converts it into a Sidebar, for example Tab Tree, the Slim Chrome height is too skinny to properly open the Navigation Bar with ease.
Allowing the user to configure the height of Slim Chrome would make it easier to use this specific scenario.

**Comment by Quicksaver** [comment]
I'd rather make it so the toolbars appear when moving the mouse over to the title area of the window.

In the meantime, you can use something like the following in Stylish:
```CSS
#theFoxOnlyBetter-slimChrome-slimmer {
  height: 15px !important;
}
```
