### ISSUE TITLE
Enhanced "Awesome Bar" suggestions not working properly in Firefox 48

### ISSUE THREAD

**Issue by ces42** [Quicksaver/The-Fox--Only-Better#188]
Firefox 48 changed the layout of the "Awesome Bar" suggestions and this seems to affect this add-on. (see attached Screenshot). The main problem is that there were more than one suggestions, but only one was partly displayed.

![bug-beyond_australis](https://cloud.githubusercontent.com/assets/19842517/17450355/00f9e374-5b60-11e6-8a38-db2c7241cf00.png)

**Comment by EMLVIRUS** [comment]
Same for me but just using 49 beta.
But for me, it is going black.

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to this. This should be fixed by [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1). Please try it out and let me know how it works for you.

**Comment by ces42** [comment]
well, it works better, although there is still to little space below site addresses.
![firefox](https://cloud.githubusercontent.com/assets/19842517/20402240/2ebf9220-acfc-11e6-843a-e913097a0290.png)

**Comment by Quicksaver** [comment]
Do you have any special styles being used, such as Stylish scripts or anything in your userChrome.css? Does that also happen if you disable all other add-ons except for Beyond Australis?

**Comment by ces42** [comment]
still the same with addons and userchrome disabled

**Comment by Quicksaver** [comment]
Does that also happen in a [clean profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)? I can't reproduce it at all, it looks as supposed for me.

**Comment by ces42** [comment]
still the same with a clean profile - maybe its an ubuntu / unity thing?

**Comment by EMLVIRUS** [comment]
@ces42 it seems not. i'm using Firefox 51 beta (64-bits) on Windows 10.
For me it looks like this:
![20161119_084230](https://cloud.githubusercontent.com/assets/16912240/20451456/77d986ee-ae34-11e6-8570-44a988118496.png)
Here is my preferences:
[thefoxonlybetter-prefs-20161119-084158.zip](https://github.com/Quicksaver/The-Fox--Only-Better/files/601158/thefoxonlybetter-prefs-20161119-084158.zip)
@Quicksaver Can you give a look?

**Comment by Quicksaver** [comment]
@EMLVIRUS it's black, all of it? Does it look like that if you disable all your other add-ons and themes? What about on a [clean profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)?

**Comment by EMLVIRUS** [comment]
Yes. All black indeed, same even if with a clean TFOB "show search engines" enabled.
[新建文本文档.txt](https://github.com/Quicksaver/The-Fox--Only-Better/files/601392/default.txt)

**Comment by Quicksaver** [comment]
@EMLVIRUS that code needs to be updated to deal with search engine icons existing in the location bar, I also have trouble with it in Nightly which also places the search engines there (regardless of Beyond Australis being enabled or not).

It's also definitely not the same as @ces42's issue.

For now you can add a ```#searchbar``` selector behind each line, so that it doesn't interfere. Something like this:
```CSS
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
/*
HELLO! This script has optional settings that you can try out if you return to its page: https://userstyles.org/styles/122214/firefox-search-bar-show-engine-names-firefox-43
*/
/* Make the one-off buttons span the full width */
#searchbar .searchbar-engine-one-off-item[tooltiptext] {
  width: 100% !important;
  height: 24px !important;
  background-image: none !important;
  padding-left: 6px !important;
  box-sizing: content-box !important;
  line-height: 1em !important;
}
/* Hide the empties */
#searchbar .searchbar-engine-one-off-item:not([tooltiptext]) {
  display: none !important;
}
/* Fix up borders */
#searchbar .searchbar-engine-one-off-item[tooltiptext], .addengine-item {
  border-bottom: 1px solid #ccc !important;
}
#searchbar .search-setting-button.search-panel-header, .addengine-item,
#searchbar .search-panel-header.search-panel-current-input {
  border-top: none !important;
  max-height: 26px !important;
  min-height: 16px !important;
  padding-top: 1px !important;
}
/* Insert descriptive name for search engine plugin */
#searchbar .searchbar-engine-one-off-item[tooltiptext]::after {
  content: attr(tooltiptext);
  margin: 5px 6px 0px !important;
  display: block !important;
}
/* Fix icon positioning */
#searchbar .searchbar-engine-one-off-item[tooltiptext] > .button-box {
  display: inline-flex !important;
  width: 16px !important;
  max-width: 16px !important;
  border: none !important;
  padding: 0 0 !important;
}
#searchbar .searchbar-engine-one-off-item[tooltiptext] > .button-box > .button-icon {
  display: block !important;
  margin-top: 4px !important;
  margin-left: -1px !important;
}
/* Lock in space for 5 search suggestions with scroll bar */
#PopupSearchAutoComplete .autocomplete-tree.plain.search-panel-tree .tree-bodybox,
#PopupSearchAutoComplete .autocomplete-tree.plain.search-panel-tree .autocomplete-treebody {
  display: flex !important;
  flex: 1 1 auto !important;
}
#PopupSearchAutoComplete .autocomplete-tree.plain.search-panel-tree .autocomplete-treebody {
  max-height: calc(5 * 1.5em) !important;
  min-height: calc(5 * 1.5em) !important;
}
#PopupSearchAutoComplete .autocomplete-tree.plain.search-panel-tree .tree-scrollbar[collapsed="true"] {
  visibility: visible !important;
}
/* User style options */
/* One column - standard spacing (built-in above) */
/* Hiding "Search for ..." */
#searchbar .search-panel-header.search-panel-current-input {
  display: none !important;
}
/* Not hiding "Add ..." engine */
/* Not hiding "Change Search Settings" */
/* Search bar tooltip text only visible on mouseover */
/* No color scheme */
```
