### ISSUE TITLE
Sometimes address bar doesn't appear in time.

### ISSUE THREAD

**Issue by nyanon** [Quicksaver/The-Fox--Only-Better#201]
Hello,
I am the one who left that comment: https://addons.mozilla.org/en-US/firefox/addon/the-fox-only-better/reviews/821631/

It's mean that delay before appearing is too big. I set short delay before appearing navigation panel "on mouse hover". Sometimes navigation panel appear immediately. But sometimes panel doesn't appear very big time, at least 5 sec or never.

I have slow CPU but enough for Firefox and other addons. (: Especially that bug (lagging) notices when couple pages loads at the same time.

I wrote small user CSS style similarly to your addon. But it demands dynamic navigation panel (or bookmark bar) size setting:

**Show bookmark's bar on mouse hover (for default Firefox theme under Windows 7)**
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#navigator-toolbox
{
  position: relative !important;
  z-index : 1 !important;
}

#content-deck
{
  position: relative !important;
  z-index : 2 !important;
  margin-top : 0px !important;
  border-top: 0.5px black solid !important;
}

#content-deck:hover
{
  margin-top : -25px !important; /* hidden navigation panel height */
}
```
As you can see you need to set **"hidden navigation panel height"** depends on your **navigation panel** height (or bookmark bar height).

**UPD**
(Result of using my user style. Appearing navigation panel on mouse hover)
<img src="http://i.imgur.com/Vafch8H.png" alt="test" width="604" height="320" />

**UPD2**
Sorry, I did mistake in my CSS style. (: Now all should works fine.

**Comment by nyanon** [comment]
**Show bookmark's bar on mouse hover (for default Firefox theme under Windows 7) v2**

**What's new:**
_fixed page's jumping on mouse hover (on showing navigation bar)_

```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#navigator-toolbox
{
  position: relative !important;
  z-index : 1 !important;
}

#content-deck
{
  position: relative !important;
  margin-top : -25px !important;
  border-top: 0.5px black solid !important;
}

#content-deck:hover
{
  z-index : 2 !important;
  margin-top : -25px !important; /* hidden navigation panel height */
}
```

**Comment by nyanon** [comment]
**Show bookmark's bar on mouse hover (for default Firefox theme under Windows 7) v3.0**
* **What's new:**
 _* fixed page's jumping on not Firefox's window hover_
  * <sub>For example: now you can set mouse pointer on system desktop panel without navigation panel jumping.</sub>
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#navigator-toolbox
{
  position: relative !important;
  z-index : 1 !important;
}

#content-deck
{
  position: relative !important;
  margin-top : -25px !important; /* hidden navigation panel height */
  border-top: 0.5px black solid !important;
}

#content-deck:hover
{
  z-index : 2 !important;
  margin-top : -25px !important; /* hidden navigation panel height */
}

#tab-view-deck:not(:hover) #content-deck
{
  z-index : 2 !important;
  margin-top : -25px !important; /* hidden navigation panel height */
}
```

**Comment by nyanon** [comment]
**Show bookmark's bar on mouse hover (for default Firefox theme under Windows 7) v3.1**

**Note:** bookmark panel should be opened for using this style.

* **What's new:**
 * _fixed regression: preventing navigation panel jumping calls navigation panel jumping on menu mouse hover_

```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#navigator-toolbox
{
  position: relative !important;
  z-index : 1 !important;
}

#content-deck
{
  position: relative !important;
  margin-top : -25px !important; /* hidden navigation panel height */
  border-top: 0.5px black solid !important;
}

#content-deck:hover
{
  z-index : 2 !important;
  margin-top : -25px !important; /* hidden navigation panel height */
}

#tab-view-deck:not(:hover) #content-deck
{
}
```
